import Head from "next/head";
import TopRatedTVShows from "../../components/TopRatedTvShows";
import axios from "axios";
import server from "@/config";

export default function TvShows({ tvShows }) {
  return (
    <>
      <Head>
        <title>Chili TV Shows</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {tvShows && tvShows.results ? (
        <TopRatedTVShows tvShows={tvShows.results} />
      ) : (
        <p>Error loading TV shows. Please try again later.</p>
      )}
    </>
  );
}

export async function getStaticProps() {
  try {
    const res = await axios(
      `${server}/tv/popular?api_key=${process.env.API_KEY}&language=en-US&page=1`
    );
    const tvShows = res.data;

    
    return {
      props: { tvShows },
    };
  } catch (error) {
    return {
      props: { tvShows: null },
    };
  }
}
