import Head from 'next/head'
import { useState, useEffect } from 'react'
import ContnetList from '../../components/ContentList'
import axios from 'axios'
import server from '../../config/index'

export default function Home({ contentType, movies }) {
  const [title, setTitle] = useState('Top Rated Movies')
  useEffect(() => {
    if (contentType === 'tv-shows') {
      setTitle('Top Rated Tv Shows')
    }
    if (contentType === 'more-movies') {
      setTitle('More Movies')
    }
  }, [contentType])
  return (
    <>
      <Head>
        <title>Chili Movies</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {movies ? (
        <ContnetList contentType={contentType} pageTitle={title}>
          {movies}
        </ContnetList>
      ) : (
        <p>Error loading movies. Please try again later.</p>
      )}
    </>
  )
}

export async function getServerSideProps({ query: { contentType } }) {
  try {
    // this sets the default to movie
    let urlType = 'movie'
    // this changes based off the route you are on.
    if (contentType === 'tv-shows') {
      urlType = 'tv'
    }
    const {
      data: { results: movies },
    } = await axios(
      `${server}/${urlType}/top_rated?api_key=${process.env.API_KEY}&language=en-US&page=1`
    )
    return {
      props: { contentType, movies },
    }
  } catch (error) {
    console.error('Error fetching movies:', error)
    return {
      props: {},
    }
  }
}
