import Head from 'next/head'
import ContnetList from '../components/ContentList'
import axios from 'axios'
import server from '../config/index'

export default function Home({ movies }) {
  return (
    <>
      <Head>
        <title>Chili Movies</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {movies ? (
        <ContnetList contentType='movie' pageTitle='Top Rated Movies'>
          {movies}
        </ContnetList>
      ) : (
        <p>Error loading movies. Please try again later.</p>
      )}
    </>
  )
}

export async function getServerSideProps() {
  try {
    const {
      data: { results },
    } = await axios(
      `${server}/movie/top_rated?api_key=${process.env.API_KEY}&language=en-US&page=1`
    )
    return {
      props: { movies: results },
    }
  } catch (error) {
    console.error('Error fetching movies:', error)
    return {
      props: { movies: null },
    }
  }
}
